# Generated by Django 3.2.5 on 2021-07-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], max_length=20),
        ),
    ]
