# Generated by Django 3.2.5 on 2021-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmaster',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
