# Generated by Django 3.2.5 on 2021-07-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationmaster_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmaster',
            options={'ordering': ['application', '-level']},
        ),
    ]
