# Generated by Django 3.2.5 on 2021-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakao_id', models.IntegerField(unique=True)),
                ('certification', models.BooleanField(null=True)),
                ('bussiness', models.BooleanField(null=True)),
                ('introduction', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('birth', models.DateField()),
                ('profile_image', models.URLField(max_length=2000, null=True)),
                ('career', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
    ]
