# Generated by Django 3.2.5 on 2021-07-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='bussiness',
            new_name='business',
        ),
    ]
