# Generated by Django 3.2.5 on 2021-07-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='profile_image',
            field=models.URLField(null=True),
        ),
    ]
